import esbuild from "esbuild";
import process from "process";
import { copyFileSync, mkdirSync, watch } from "node:fs";
import { builtinModules } from "node:module";
import { join } from "node:path";

const banner =
  "/*\n" +
  "THIS IS A GENERATED/BUNDLED FILE BY ESBUILD\n" +
  "if you want to view the source, please visit the github repository of this plugin\n" +
  "*/";

const prod = process.argv[2] === "production";
const devPluginDir = "dev-plugin";
const devPluginAssets = ["manifest.json", "styles.css"];

function syncDevPluginAsset(relativePath) {
  copyFileSync(relativePath, join(devPluginDir, relativePath));
  console.log(`[dev-plugin] synced ${relativePath}`);
}

function syncDevPluginAssets() {
  mkdirSync(devPluginDir, { recursive: true });
  for (const asset of devPluginAssets) {
    syncDevPluginAsset(asset);
  }
}

function watchDevPluginAssets() {
  for (const asset of devPluginAssets) {
    watch(asset, () => {
      try {
        syncDevPluginAsset(asset);
      } catch (error) {
        console.error(`[dev-plugin] failed to sync ${asset}:`, error);
      }
    });
  }
}

if (!prod) {
  syncDevPluginAssets();
  watchDevPluginAssets();
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  loader: {
    ".wasm": "binary",
  },
  outfile: prod ? "main.js" : `${devPluginDir}/main.js`,
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
